export const Cities = [
  "Richmond",
  "San Pablo",
  "El Sobrante",
  "Pinole",
  "El Cerrito",
  "Hercules",
  "Berkeley",
  "Albany",
  "San Quentin",
  "Rodeo",
  "San Rafael",
  "Belvedere Tiburon",
  "Crockett",
  "Corte Madera",
  "Larkspur",
  "Kentfield",
  "Vallejo",
  "Emeryville",
  "Greenbrae",
  "San Francisco",
  "Sausalito",
  "Oakland",
  "Ross",
  "Port Costa",
  "Martinez",
  "Mill Valley",
  "San Anselmo",
  "Orinda",
  "Piedmont",
  "Novato",
  "Fairfax",
  "Canyon",
  "Alameda",
  "Lafayette",
]
